### ISSUE TITLE
Terminal becomes completely non-responsive after quitting program. 

### ISSUE THREAD

**Issue by aPeter1** [FrandsenGroup/beams#183]
Check sentry logs, I wasn't able to immediately recreate this on my computer.

**Comment by benfrandsen** [comment]
Sure, I'll send it over slack (.yml file types not accepted here).

**Comment by aPeter1** [comment]
Hmmm so recreating your conda environment didn't do it. What OS are you on? 10 or 11?

**Comment by benfrandsen** [comment]
Windows 10. If it's not an issue for anyone else, we can probably just chalk this up to something flukey with my computer.

**Comment by aPeter1** [comment]
This is why I created the 'mystery' tag. Very interesting. You could try making sure everything is updated and just creating a new environment. But until this happens again it may be hard to nail down exactly what is happening.

**Comment by aPeter1** [comment]
Out of curiosity, are you still having this issue Ben?

**Comment by benfrandsen** [comment]
I can't remember the last time it happened, so maybe we're good!
