### ISSUE TITLE
Adjustments to built-in fitting functions

### ISSUE THREAD

**Issue by benfrandsen** [FrandsenGroup/beams#193]
Please see attached notes for modifications to the built-in fitting functions
[notes_on_beams_functions.txt](https://github.com/FrandsenGroup/beams/files/8445812/notes_on_beams_functions.txt)
.

**Comment by aPeter1** [comment]
So I'm thinking its probably not worth it to use the unicode character for 'nu' right? I imagine people would be accidentally typing v and ending up with two parameters 😂

**Comment by aPeter1** [comment]
Also, do you want j0(x) to represent sin(x)/x just generally? Is that a well known thing? We could.... I'm trying to think of a good way to show that. Maybe like a ComboBox and a LineEdit next to each other, and in the combo box is a list of functions (like j0) and when they click it it will show what the implementation is in the line edit  ( j0(x) = sin(x)/x ). And then we could have similiar functionality like we have now where they can specify a new function but I'd make that a separate issue.

**Comment by aPeter1** [comment]
Changing my thoughts on this. Sympy has a builtin function like sin and cos call jn where the user can pass the first argument as an int (in our case 0) and then the actually expression they are passing in. At first I figured we would just abstract that away and let the user type 'j0' and in the backend we replace it with 'jn(0,'. However, there are a ton of other methods as well that I don't necessarily want to handle myself but may be useful to the users.

If we just redirect users to that documentation they can specify a lot more functions in their expression then we would care to implement on our end. So typing 'a * jn(0, 2*pi*....)' may not look as pretty in the box but it gives them more freedom.

**Comment by aPeter1** [comment]
I think we had talked about the user being able so specify custom functions of some sort that they can use so that would still be a good feature to work on in the future.

**Comment by aPeter1** [comment]
I added this combobox, when the user selects a function it inserts it at their cursor. If they hover over it they will see a more detailed description.
![image](https://user-images.githubusercontent.com/42580833/162597537-734b4c89-bd11-4972-a9c4-508222a975af.png)

**Comment by aPeter1** [comment]
I added ones I think were somewhat relevant to that combobox, technically the user can use a lot more that I could add in explicitly. But so long as they know it exists with scipy and numpy they can use it

**Comment by benfrandsen** [comment]
Some feedback after playing around with this.
- It's look really great!
- The default values look good; the only thing I noticed is that for Gaussian KT, sigma is 0.1 when it should be 1.0
- For Internal Cos and Internal Bessel, could we make the T and L in lambdaT and lambdaL be subscripts? 
- I prefer to keep j0 and have the backend convert it to jn(0, arg). There are certain physical situations where j0 is the right function to use, but that's not the case for any of the other bessel functions, as far as I know. So there's no need to generalize it at the expense of simplicity for the user.
- Along those same lines, I think the combobox isn't actually necessary, although it wasn't a bad idea to try out. It's just that most of those are rather exotic functions which would never be physically justifiable to use when fitting asymmetry data. I think if the readme materials make it clear that sympy functions and notation are accepted, then we can just refer the user to the sympy documentation and they can use it if the need arises.
- How hard would it be to change the font for the math expressions to a serif font? I don't love the way that pi displays, and I don't like how the Greek letter nu displays almost exactly like a v. Not a huge deal, though.

**Comment by aPeter1** [comment]
- 🙏 
- 👍 
- 👍
- 👍
- 👍
- 👍

**Comment by aPeter1** [comment]
Minus the font change, I think this should be good now 👍
