### ISSUE TITLE
.bin files from PSI are not being converted correctly

### ISSUE THREAD

**Issue by aPeter1** [FrandsenGroup/beams#205]
I'll need to update the executable for this, luckily they had a great library that was easy to use (and  by library I mean two files, things are so much easier when you don't write your code in C). On the BRIGHT side I now have the opportunity to document how this is done.

**Comment by aPeter1** [comment]
As far as I can tell the files I downloaded to test on did not have histogram titles (which is what was missing and causing it to fail). So I guess I'll just give them numbers. Also, someone wrote a python wrapper for the PSI library a few months ago (it's a pretty small library) so I'll probably just use that and make beams easier to maintain.

**Comment by aPeter1** [comment]
Kind of jealous I didn't think to do that first, I might do that for the mud files after graduation 😂

**Comment by aPeter1** [comment]
Is there a  good way to guestimate the first and last bins for calculating background? Like,  first bin that isn't 0 to 5 bins before t0 maybe? These values are not included in the bin  or mdu files.

**Comment by benfrandsen** [comment]
Strange that the background bins aren't provided. I would say a safe guess is 10% of the way to t0 to 90% of the way. We don't want to get to close to either endpoint, where things are often a bit strange.

**Comment by aPeter1** [comment]
I agree, this is a link to their documentation for the class you use to read the files. I couldn't see anything except methods where you pass IN the bckgrd bins. Tis weird.

http://lmu.web.psi.ch/docu/manuals/bulk_manuals/software/Class_MuSR_PSI/index.html

**Comment by aPeter1** [comment]
@benfrandsen typically the runs start with a section of zeroes which I assume would throw off the background calculation. What if we did 10% or when we get the first non-zero value, whichever comes later for the starting value.

**Comment by benfrandsen** [comment]
Yes, we should definitely exclude any leading zeroes. Let's start 5% of the way from the first nonzero value.
