### ISSUE TITLE
Black line for fit in dark mode is hard to see

### ISSUE THREAD

**Issue by aPeter1** [FrandsenGroup/beams#206]
Let's find a beautiful shade of gray (there are upwards of fifty I have heard) to replace the black. OR go crazy and use a nice hot pink. Also, add the question mark to the download file dialog and come up with a ridiculous equation for the fitting panel hint text for user defined equations.

**Comment by aPeter1** [comment]
Realizing I never actually changed that equation 😂, Ben, do you have a recommendation?

**Comment by benfrandsen** [comment]
Maybe it's too late, but if you want to put in a default equation, I would just go with a * exp(-lambda * t).
