### ISSUE TITLE
Divide by zero error when fitting

### ISSUE THREAD

**Issue by Emzapp** [FrandsenGroup/beams#214]
I'm not really sure what is happening here, but the fitting function isn't working. I loaded in data like normal and worked to fit, but it doesn't do anything. There's a bunch of errors that pop up in the command line that I couldn't make a lot of sense of, and I'm including them here.

I run on mac, with python3.
<img width="906" alt="Screen Shot 2022-05-03 at 11 44 23 AM" src="https://user-images.githubusercontent.com/84045856/166510162-f2755de1-881e-42f5-bfbb-b3ead0a0dcb0.png">
<img width="909" alt="Screen Shot 2022-05-03 at 11 44 15 AM" src="https://user-images.githubusercontent.com/84045856/166510173-ab903fd4-ec5f-4595-b8ab-c336ee5210c0.png">

**Comment by Emzapp** [comment]
The files uploaded out of order, the top one is after the bottom one.

**Comment by Emzapp** [comment]
It seems to work when I don't try to change the time binning. At least, I did all the exact same things this time around except for that and it worked fine.

**Comment by aPeter1** [comment]
'Residuals are not finite at the initial point', lovely. I wonder if the sentry exception would say what the fit config was at the time

**Comment by jaredblack** [comment]
Hah yeah good ol Python. I'll look into this though.
