### ISSUE TITLE
FileNotFound error when converting .msr files on Mac

### ISSUE THREAD

**Issue by Emzapp** [FrandsenGroup/beams#216]
so I tried to use the convert feature for the first time in a while today and it is broke. Won't work. I've attached the relevant error that came up when trying to use the feature.
<img width="823" alt="Screen Shot 2022-07-24 at 9 34 12 AM" src="https://user-images.githubusercontent.com/84045856/180657136-42827b41-8727-430e-a7f4-c9b156c240e8.png">

**Comment by aPeter1** [comment]
Interesting, can you verify what the correct path to that file is? As far as it's location in the repo, (beams/app/resources/binaries/TRIUMF_MAC) that is correct so it must be generating the rest of that path incorrectly.
