### ISSUE TITLE
UI Issue with graphing

### ISSUE THREAD

**Issue by Emzapp** [FrandsenGroup/beams#241]
Both of the windows on the side containing the names of files and the data being plotted on the main screen have the scroll slider on the bottom block the last entry, at least on Mac. This should be fixed. I attacehd a screenshot of the blocked entries.
<img width="426" alt="Screen Shot 2022-10-29 at 4 45 26 PM" src="https://user-images.githubusercontent.com/84045856/198856527-553c305d-d8ec-421e-9100-60d0c63b70e0.png">

**Comment by aPeter1** [comment]
@Emzapp It works correctly on my mac (@jaredblack yours?), does this consistently happen?

**Comment by aPeter1** [comment]
After I updated my mac I also got this issue, I'll take a closer look at this
