### ISSUE TITLE
Starting time for asymmetry plots won't go above 0.2 us

### ISSUE THREAD

**Issue by benfrandsen** [FrandsenGroup/beams#254]
##### Note: Every field here is optional, but the more info you provide, the easier it will be to find and fix your bug. Feel free to delete any fields you can not fill out.

**Describe the bug**
The program won't let me view the asymmetry with any starting time value greater than 0.2. We should change it so that any starting and ending time contained within the data window are acceptable. Thanks!

**Comment by aPeter1** [comment]
Weird, like the x_min value? Is there a particular data set that fails for you?

**Comment by benfrandsen** [comment]
Take a look at the screen recording at https://byu.box.com/s/c672lwr307cvirpn7pzdih3x25z1mbg4 where I demonstrate the bug (and discover a second bug in the process, haha). Hopefully it's not too hard a fix!

**Comment by aPeter1** [comment]
Perfect! I'll look into this tonight

**Comment by aPeter1** [comment]
Ah and the second one looks like its only an issue if the x_min is greater then half of x_max. I'm hoping both of these are simple

**Comment by aPeter1** [comment]
I pushed a commit to master, let me know if its fixed

**Comment by benfrandsen** [comment]
Looks like it's fixed! Thank you!

**Comment by aPeter1** [comment]
Woot woooot
