### ISSUE TITLE
PSI issues

### ISSUE THREAD

**Issue by aPeter1** [FrandsenGroup/beams#257]
1. When loading PSI data, the user is prompted to select histograms to combine. However, the only option seems to be a continuous range of integer labels for the  (e.g. 1-8), when sometimes we will need a discontinuous selection (e.g. 1, 3 for the "front" and 5, 7 for the "back" detectors). Could you update this to accept either a continuous range or a discrete list?
3. When looking for runs from the PSI website, the search doesn't always work. For example, if I search for runs in 2015 on GPD with V2O3 as a keyword, nothing shows up, yet there's a whole bunch of them when I search at http://musruser.psi.ch/cgi-bin/SearchDB.cgi .
5. For the LEM instrument, the search seems to be working well, but the files do not download successfully. I believe this is because a minimum binning value of 10 must be used when downloading in the PSI-BIN format from LEM. Could the code be updated such that when LEM is selected, a bin value of 10 is passed to the PSI server?

**Comment by aPeter1** [comment]
Number 2 was fixed by adjusting how I read the search results (they changed the table format). On a side note, I'm tempted to just have the button go straight to the web page for downloading files. This obviously means future changes won't affect us but has the downside that beams won't immediately add the files in after download so I'll leave it up to you as to whether or that's the better route.

**Comment by aPeter1** [comment]
You were right about the binning! I'll need to test all the areas to make sure they work

**Comment by aPeter1** [comment]
@benfrandsen feel free to add additional comments regarding my suggestion above, I'll close this since the original bugs *should* be fixed now

**Comment by benfrandsen** [comment]
Thanks for the quick turnaround! I'm totally fine just linking to the respective facility databases if it becomes tricky keeping up with changes. Let's leave it how it is now, but if there are problems in the future, we'll just link to the website and not worry about direct downloads into BEAMS.
